### ISSUE TITLE
PA Review: Song CRUD 

### ISSUE THREAD

**Issue by therealmeyer** [therealmeyer/SonicStratus#3]
- [ ] Users can upload songs
- [ ] Songs can be edited or deleted
- [ ] Adequate styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds to demonstrate the feature

**Comment by therealmeyer** [comment]
Uploading takes FOREVER! Anyway to fix that?

**Comment by AAlfarho** [comment]
Kudos on the amazing job implementing your track feature, image-audio upload worked great without any hiccup for me, I was able to upload an 11MB track without any issue.
The points to complete this MVP are all done, however, the navigation is not that **smooth.**

- [ ] My concern is the fact that you are loading ~100 MB on the track index page, the total loading time is around 40s, we don't even know if the user will play those songs, we should lazy load the audio files.

From our conversation, it appears you already have found a solution for this. 
With that in mind and considering we are hitting for MVP's I'll close this issue.
