### ISSUE TITLE
PA Review: User Show Pages

### ISSUE THREAD

**Issue by therealmeyer** [therealmeyer/SonicStratus#5]
- [ ] Shows list of songs for the user
- [ ] Adequate styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds to demonstrate the feature

**Comment by AAlfarho** [comment]
The user show page is almost complete! There are only a couple of details we need to address before moving on.

- [x] Let's add a couple more songs to the demo user profile. As well as a profile picture and header.
- [x] Log in as the demo user, go to your profile, and then click on `Flume's`, the site will crash. `Cannot read property 'profile_img_url' of undefined`.


Feel free to check the items on this list and assign this issue back to me once the mentioned points are addressed.

**Comment by AAlfarho** [comment]
Great job!

We can now consider this feature to ready!
